spring.application.name=Secure-Document-Management-System

spring.datasource.url=jdbc:mysql://localhost:3306/document_management

spring.datasource.username=root

spring.datasource.password=17072004


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

file.upload-dir=uploads
# AES Secret Key
aes.secret=12345678901234567890123456789012